#############################
# names of results
#############################

####
# within host models
#####

MINIMAL_FIXED_NAME = minimal_fixed
MINIMAL_VISVAR_NAME = minimal_visvar
MINIMAL_STERILIZING_NAME = minimal_sterilizing
MINIMAL_DELETERIOUS_FIXED_NAME = minimal_deleterious_fixed
MINIMAL_DELETERIOUS_VAR_NAME = minimal_deleterious_var
MINIMAL_COMP_NAIVE_NAME = minimal_comp_naive
MINIMAL_TEST_NAME = minimal_test

MINIMAL_VISVAR_NAME = minimal_visvar


MINIMAL_BN_NAMES = $(MINIMAL_STERILIZING_NAME)
MINIMAL_VB_NAMES = $(MINIMAL_VISVAR_NAME) $(MINIMAL_FIXED_NAME)

SENSITIVITY_NAMES = $(MINIMAL_FIXED_NAME) $(MINIMAL_VISVAR_NAME)

#############################
# Default parameter values - mimimal model
#############################
DEFAULT_MWH_BOTTLENECKS = 1 3 10 50 100 200
DEFAULT_MWH_VB_RATIOS = 1 3 10 50 100 200

DEFAULT_T_M = 2
DEFAULT_T_N = 6
DEFAULT_P_C = 0
DEFAULT_C_MAX = 4e8
DEFAULT_R0_WH = 5
DEFAULT_D_V = 4

DEFAULT_Z_WT = 0.95
DEFAULT_Z_MUT = 0
DEFAULT_MUT_WT_NEUT_RATIO = 0

DEFAULT_MU = 0.33e-5
DEFAULT_K = 6
DEFAULT_F = 1
DEFAULT_CROSS_IMM = 0
DEFAULT_R_W = 100
DEFAULT_R_M = 100
DEFAULT_E_W = 0
DEFAULT_E_M = 0
DEFAULT_TRANS_THRESHOLD = 1e7

# value of the max instantaneous transmission
# probability below which we
# say "wasn't ever transmissible"
DEFAULT_TRANS_CUTOFF = 5e-2

# viral load at which transmission
# given contact with a naive host
# occurs with 50% probability
DEFAULT_TD50 = 1e8

DEFAULT_DETECTION_THRESHOLD = 1e-2
DEFAULT_DETECTION_LIMIT = 1e5
DEFAULT_T_FINAL = 50
DEFAULT_LEAP_TIMESTEP = 0.01
DEFAULT_INOCULATOR_LEAP_TIMESTEP = 0.01
DEFAULT_BOTTLENECK = 1
DEFAULT_RNG_SEED = 33252
DEFAULT_VB_RATIO = 10 # ratio of bottleneck to n encounters iga
DEFAULT_EMERGENCE_THRESHOLD = 4 # number of virions to count as an emergence near-certain to survive stochastic loss

DEFAULT_F_MUT = 9e-5
DEFAULT_USE_Z_MUT = -1

MINIMAL_NITER = 250000

MINIMAL_TEST_LEAP_TIMESTEP = 0.01
MINIMAL_TEST_T_FINAL = 50


#############
# minimal within host model variants:
# parameter definitions
##############
MINIMAL_FIXED_T_M = 0

MINIMAL_VISVAR_RNG_SEED = 12
MINIMAL_FIXED_RNG_SEED = 14

MINIMAL_STERILIZING_RNG_SEED = 212
MINIMAL_STERILIZING_NITER = 100000
MINIMAL_STERILIZING_K = 20
MINIMAL_STERILIZING_T_M = 0
MINIMAL_STERILIZING_Z_WT = 0
MINIMAL_STERILIZING_CROSS_IMM = 0
MINIMAL_STERILIZING_LEAP_TIMESTEP = 0.001
MINIMAL_STERILIZING_INOCULATOR_LEAP_TIMESTEP = 0.01

MINIMAL_COMPROMISED_RNG_SEED = 23587
MINIMAL_COMPROMISED_NITER = 1000
MINIMAL_COMPROMISED_P_C = 0.6
MINIMAL_COMPROMISED_CROSS_IMM = 0.75
MINIMAL_COMPROMISED_K = 0.5
MINIMAL_COMPROMISED_T_FINAL = 100
MINIMAL_COMPROMISED_T_N = 101

MINIMAL_COMP_NAIVE_RNG_SEED = 23587
MINIMAL_COMP_NAIVE_NITER = 1000
MINIMAL_COMP_NAIVE_P_C = 0.6
MINIMAL_COMP_NAIVE_CROSS_IMM = 0.75
MINIMAL_COMP_NAIVE_K = 0.5
MINIMAL_COMP_NAIVE_T_FINAL = 100
MINIMAL_COMP_NAIVE_T_N = 101
MINIMAL_COMP_NAIVE_T_M = 6

MINIMAL_TEST_RNG_SEED = 325
MINIMAL_TEST_R0_WH = 5 #4.04551
MINIMAL_TEST_R_W = 2914.81
MINIMAL_TEST_R_M = 2914.81
MINIMAL_TEST_MU = 0 #8.82457e-06
MINIMAL_TEST_D_V= 7.34099
MINIMAL_TEST_K = 7.60462
MINIMAL_TEST_T_M = 2.27212
MINIMAL_TEST_T_N = 8.1794
MINIMAL_TEST_CROSS_IMM = 0.166546
MINIMAL_TEST_Z_WT = 0.860967
MINIMAL_TEST_MUT_WT_NEUT_RATIO = 0.0298177
MINIMAL_TEST_C_MAX = 4e8 #4.7677e+09


####################################
# params for sensitivity analysis
####################################

SENSITIVITY_BOTTLENECKS = 1 3 10 50
SENSITIVITY_NITER = 50000
SENSITIVITY_N_PARAMSETS = 10

# parameter ranges for sensitivity

DEFAULT_R0_WH_MIN = 5
DEFAULT_R0_WH_MAX = 15

DEFAULT_R_W_MIN = 50
DEFAULT_R_W_MAX = 500

DEFAULT_MU_MIN = 0.33e-6
DEFAULT_MU_MAX = 0.33e-4

DEFAULT_D_V_MIN = 2
DEFAULT_D_V_MAX = 8

DEFAULT_K_MIN = 0
DEFAULT_K_MAX = 20

DEFAULT_CROSS_IMM_MIN = 0.5
DEFAULT_CROSS_IMM_MAX = .99

DEFAULT_T_M_MIN = 2
DEFAULT_T_M_MAX = 4.5

DEFAULT_T_N_MIN = 6
DEFAULT_T_N_MAX = 9

DEFAULT_C_MAX_MIN = 4e7
DEFAULT_C_MAX_MAX = 4e9

DEFAULT_Z_WT_MIN = 0.70
DEFAULT_Z_WT_MAX = 0.99

DEFAULT_VB_RATIO_MIN = 1
DEFAULT_VB_RATIO_MAX = 1

DEFAULT_TRANS_THRESHOLD_MIN = 1e6
DEFAULT_TRANS_THRESHOLD_MAX = 1e8

DEFAULT_TD50_MIN = 1e7
DEFAULT_TD50_MAX = 1e9

DEFAULT_Z_MUT_Z_WT_RATIO_MIN = 0.5
DEFAULT_Z_MUT_Z_WT_RATIO_MAX = 0.9



# visvar sensitivity analysis
MINIMAL_VISVAR_R0_WH_MIN = 5
MINIMAL_VISVAR_R0_WH_MAX = 15
MINIMAL_VISVAR_R_W_MIN = 10
MINIMAL_VISVAR_R_W_MAX = 500

MINIMAL_VISVAR_MU_MIN = 0.33e-6
MINIMAL_VISVAR_MU_MAX = 0.33e-4

MINIMAL_VISVAR_D_V_MIN = 2
MINIMAL_VISVAR_D_V_MAX = 8

MINIMAL_VISVAR_K_MIN = 3
MINIMAL_VISVAR_K_MAX = 20

MINIMAL_VISVAR_CROSS_IMM_MIN = 0.5
MINIMAL_VISVAR_CROSS_IMM_MAX = 1

MINIMAL_VISVAR_T_M_MIN = 2
MINIMAL_VISVAR_T_M_MAX = 4.5

MINIMAL_VISVAR_T_N_MIN = 6
MINIMAL_VISVAR_T_N_MAX = 9

MINIMAL_VISVAR_C_MAX_MIN = 4e7
MINIMAL_VISVAR_C_MAX_MAX = 4e9

MINIMAL_VISVAR_Z_WT_MIN = 0.70
MINIMAL_VISVAR_Z_WT_MAX = 0.99

MINIMAL_VISVAR_Z_MUT_Z_WT_RATIO_MIN = 0.5
MINIMAL_VISVAR_Z_MUT_Z_WT_RATIO_MAX = 0.9

MINIMAL_VISVAR_VB_RATIO_MIN = 1
MINIMAL_VISVAR_VB_RATIO_MAX= 50



# fixed immunity sensitivity analysis
MINIMAL_FIXED_R0_WH_MIN = 5
MINIMAL_FIXED_R0_WH_MAX = 15

MINIMAL_FIXED_R_W_MIN = 10
MINIMAL_FIXED_R_W_MAX = 500

MINIMAL_FIXED_MU_MIN = 0.33e-6
MINIMAL_FIXED_MU_MAX = 0.33e-4

MINIMAL_FIXED_D_V_MIN = 2
MINIMAL_FIXED_D_V_MAX = 8

MINIMAL_FIXED_K_MIN = 3
MINIMAL_FIXED_K_MAX = 16

MINIMAL_FIXED_CROSS_IMM_MIN = 0.5
MINIMAL_FIXED_CROSS_IMM_MAX = 1

MINIMAL_FIXED_T_M_MIN = 0
MINIMAL_FIXED_T_M_MAX = 1

MINIMAL_FIXED_T_N_MIN = 6
MINIMAL_FIXED_T_N_MAX = 9

MINIMAL_FIXED_C_MAX_MIN = 1e8
MINIMAL_FIXED_C_MAX_MAX = 1e9

MINIMAL_FIXED_Z_WT_MIN = 0.70
MINIMAL_FIXED_Z_WT_MAX = 0.99

MINIMAL_FIXED_Z_MUT_Z_WT_RATIO_MIN = 0.5
MINIMAL_FIXED_Z_MUT_Z_WT_RATIO_MAX = 0.9

MINIMAL_FIXED_VB_RATIO_MIN = 1
MINIMAL_FIXED_VB_RATIO_MAX = 50


######################################
# replication selection probability
# simulation parameters
######################################
REPL_NITER = 250000
REPL_T_FINAL = 3
REPL_T_MS = 0 0.25 0.5 1 1.5 2 2.5 3
REPL_KS = 0.5 1 2 4 8

######################################
# chain model parameters
######################################

N_CHAINS = 1000
SPLIT_N_CHAINS = 250
# parallelize chain simulations for four cores

DEFAULT_CHAIN_BOTTLENECK = 1
DEFAULT_CHAIN_LENGTH = 60000

DEFAULT_IMMUNE_HISTORIES = -0.8 -0.5 0
DEFAULT_IMMUNE_HISTORY_DISTRIBUTION = 0.2 0.2 0.2 0.4

DEFAULT_CHAIN_CONTACT_RATE = 1

DEFAULT_CHAIN_MUT_MEAN = 0.0
DEFAULT_CHAIN_MUT_SD = 0.08
DEFAULT_CHAIN_INIT_PHEN = 0.0
DEFAULT_CHAIN_ANTIGENIC_SCALE = 0.01

DRIFT_CHAIN_Z_WT = 0
DRIFT_CHAIN_VB_RATIO = 10
DRIFT_CHAIN_K = 25
DRIFT_CHAIN_LEAP_TIMESTEP = 0.01
DRIFT_CHAIN_IMMUNE_HISTORIES = 0
DRIFT_CHAIN_IMMUNE_HISTORY_DISTRIBUTION = 0 1.0
DRIFT_CHAIN_RNG_SEED = 3245

CONSTANT_CHAIN_Z_WT = 0
CONSTANT_CHAIN_VB_RATIO = 1
CONSTANT_CHAIN_BOTTLENECK = 10
CONSTANT_CHAIN_K = 25
CONSTANT_CHAIN_T_M = 0
 CONSTANT_CHAIN_LEAP_TIMESTEP = 0.01
CONSTANT_CHAIN_RNG_SEED = 23492852
CONSTANT_CHAIN_T_FINAL = 200  ## long infections when R_WH ~= 1


PT_CHAIN_Z_WT = 0.95
PT_CHAIN_VB_RATIO = 10
PT_CHAIN_K = 25
PT_CHAIN_T_M = 2
PT_CHAIN_LEAP_TIMESTEP = 0.01
PT_CHAIN_RNG_SEED = 938238


BETTER_TOGETHER_CHAIN_Z_WT = 0.95
BETTER_TOGETHER_CHAIN_K = 25
BETTER_TOGETHER_CHAIN_T_M = 0
BETTER_TOGETHER_CHAIN_LEAP_TIMESTEP = 0.01
BETTER_TOGETHER_RNG_SEED = 4034
BETTER_TOGETHER_CHAIN_VB_RATIO = 10


###############################
# other generic info
###############################
PUBLIC_REPO_URL = https://github.com/dylanhmorris/asynchrony-influenza
PUBLIC_DATA_URL = https://doi.org/10.17605/OSF.IO/jdsbp/
